ui/core/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import reverse_lazy

from .forms.account import LoginForm
from .views import account, dashboard, alert, asset, plots, variable, plot

urlpatterns = [

    # /account
    re_path(r'^account/login/?$',
        auth_views.LoginView.as_view(
            template_name='account/login.html',
            authentication_form=LoginForm,
        ),
        name='account.login'),
    re_path(r'^account/logout/?$',
        auth_views.LogoutView.as_view(
            next_page=settings.LOGIN_URL
        ), name='account.logout'),

    re_path(r'^account/reset_password/',
        auth_views.PasswordResetView.as_view(success_url=reverse_lazy('password_reset_done'), template_name="registration/password_reset_form.html"),
        name="auth_password_reset"),

    re_path(r'^account/reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), 
        name="password_reset_done"),

    re_path(r'^account/reset/confirm/(?P<uidb64>[^/.]+)/(?P<token>[^/.]+)/',
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('password_reset_complete'), template_name="registration/password_reset_confirm.html"), 
        name="password_reset_confirm"),

    re_path(r'^account/reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), 
        name="password_reset_complete"),

    re_path(r'^account/myaccount/?$', account.my_account, name='account.my_account'),
    re_path(r'^account/preferences/?$', account.preferences, name='account.preferences'),
    re_path(r'^account/users/?$', account.users, name='account.users'),
    re_path(r'^account/default', account.default_page, name='account.default'),
    re_path(r'^account/edit_user/(?P<user_id>[^/.]*)/?', account.my_account, name='account.edit_user'),
    re_path(r'^account/add_user/?', account.my_account, name='account.add_user'),
    re_path(r'^account/delete_user', account.delete_user, name='account.delete_user'),
    re_path(r'^account/ajax/users', account.user_list, name='account.user_list'),

    # /dashboard
    re_path(r'^hotlist/?$', dashboard.overview, name='overview'),
    re_path(r'^dashboard/?$', dashboard.default_check, name='default_check'),
    re_path(r'^system/(?P<group_id>\d+)?$', dashboard.system_overview, name='dashboard.system_overview'),
    re_path(r'^system/ajax/system_overview_preference', dashboard.update_system_overview_preference, name='dashboard.update_system_overview_preference'),
    re_path(r'^system/power/(?P<platform_id>[^/.]+)/?', dashboard.power_details, name='dashboard.power_details'),
    re_path(r'^system/ajax/update_alert_disposition', dashboard.update_alert_by_disposition, name='dashboard.update_alert_by_disposition'),

    re_path(r'^system/backup_database', dashboard.backup_database, name='dashboard.backup_database'),
    re_path(r'^system/execute_backup_database', dashboard.execute_backup_database, name='dashboard.execute_backup_database'),

    # /alert
    re_path(r'^alert/resolve/(?P<alert_id>[^/.]+)/?', alert.resolve_alert_view, name='alert.resolve'),
    re_path(r'^alert/acknowledge/?', alert.acknowledge, name='alert.acknowledge'),
    re_path(r'^alert/update_status/?', alert.update_status, name='alert.update_status'),
    re_path(r'^alert/(?P<alert_id>\d+)/$', alert.detail, name='alert.detail'),
    re_path(r'^alert/(?P<alert_id>\d+)/(?P<is_resolve>[^/.]+)/?', alert.detail, name='alert.detail'),
    re_path(r'^alert/save_note/(?P<alert_id>\d+)/?', alert.save_note, name='alert.save_note'),
    re_path(r'^alert/ajax/get_notes/(?P<alert_id>\d+)/?', alert.get_notes, name='alert.get_notes'),
    re_path(r'^alert/ajax/get_occurrences/(?P<alert_id>\d+)/?', alert.get_occurrences, name='alert.get_occurrences'),
    re_path(r'^alert/ajax/view_trigger/(?P<trigger_id>[^/.]+)/?', alert.view_trigger, name='alert.view_trigger'),
    re_path(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    re_path(r'^alert/create_manual/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', alert.create_manual, name='alert.create_manual'),
    re_path(r'^alert/manage_subscriptions/(?P<asset_id>\d+)/?', alert.manage_subscriptions, name='alert.manage_subscriptions'),
    re_path(r'^alert/edit_trigger/(?P<trigger_id>\w+)/(?P<asset_id>\w+)/$', alert.edit_trigger, name='alert.edit_trigger'),
    re_path(r'^alert/edit_trigger/(?P<trigger_id>[^/.]+)/?', alert.edit_trigger, name='alert.edit_trigger'),
    re_path(r'^alert/edit_trigger/?$', alert.edit_trigger, name='alert.edit_trigger'),
    re_path(r'^alert/clone_trigger/(?P<trigger_id>[^/.]+)/?', alert.clone_trigger_page, name='alert.clone_trigger_page'),
    re_path(r'^alert/execute_clone_trigger/?', alert.execute_clone_trigger, name='alert.execute_clone_trigger'),
    re_path(r'^alert/manage_triggers/?$', alert.manage_triggers, name='alert.manage_triggers'),
    re_path(r'^alert/ajax/trigger_list/?$', alert.trigger_list, name='alert.trigger_list'),
    re_path(r'^alert/ajax/delete_trigger/?$', alert.delete_trigger, name='alert.delete_trigger'),
    re_path(r'^alert/ajax/purge_trigger/?$', alert.purge_trigger, name='alert.purge_trigger'),
    re_path(r'^alert/export_triggers/?$', alert.export_triggers, name='alert.export_triggers'),
    re_path(r'^alert/import_triggers/?$', alert.import_triggers, name='alert.import_triggers'),
    re_path(r'^alert/confirm_import_triggers/?$', alert.confirm_import_triggers, name='alert.confirm_import_triggers'),
    re_path(r'^alert/do_import_triggers/?$', alert.do_import_triggers, name='alert.do_import_triggers'),
    re_path(r'^alert/ajax/trigger_variable_list/(?P<trigger_id>[^/.]+)/?', alert.trigger_variable_list, name='alert.trigger_variable_list'),
    re_path(r'^alert/ajax/saved_variable_list/?', alert.saved_variables_list, name='alert.saved_variables_list'),
    re_path(r'^alert/ajax/alert_notification_list/(?P<alert_id>[^/.]+)/?', alert.alert_notification_list, name='alert.alert_notification_list'),
    re_path(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    re_path(r'^alert/ajax/get_trigger_by_id/(?P<trigger_id>[^/.]+)/?', alert.get_trigger_by_id, name='alert.get_trigger_by_id'),
    re_path(r'^alert/create_redmine_issue/(?P<alert_id>\d+)/?$', alert.create_redmine_issue, name='alert.create_redmine_issue'),
    re_path(r'^alert/confirm_redmine_issue/(?P<alert_id>\d+)/?$', alert.confirm_redmine_issue, name='alert.confirm_redmine_issue'),
    re_path(r'^alert/ajax/redmine_trackers/(?P<project_id>\d+)/?$', alert.redmine_trackers, name='alert.redmine_trackers'),
    re_path(r'^alert/ajax/redmine_tracker_details/(?P<tracker_id>\d+)/?$', alert.redmine_tracker_details, name='alert.redmine_tracker_details'),
    re_path(r'^alert/ajax/refresh_notifications/?', alert.refresh_notifications, name='alert.refresh_notifications'),
    re_path(r'^redmine/confirm_redmine_issue/(?P<issue_id>\d+)/?$', alert.confirm_redmine, name='redmine.confirm_redmine'),

    # /asset
    re_path(r'^asset/overview/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.overview, name='asset.overview'),
    re_path(r'^asset/parsed_data/(?P<asset_id>[^/.]+)/?', asset.parsed_data, name='asset.parsed_data'),
    re_path(r'^asset/parsed_data_for_file/(?P<asset_id>[^/.]+)/?', asset.parsed_data_for_file, name='asset.parsed_data_for_file'),
    re_path(r'^asset/parsed_data_for_plot/(?P<asset_id>[^/.]+)/?', asset.parsed_data_for_plot, name='asset.parsed_data_for_plot'),
    re_path(r'^asset/group/(?P<group_id>[^/.]+)/?', asset.group_overview, name='asset.group_overview'),
    re_path(r'^asset/map/(?P<group_id>[^/.]+)/?', asset.group_mooring_locations, name='asset.group_mooring_locations'),
    re_path(r'^asset/plot-data/?', asset.plot_data, name='asset.plot_data'),
    re_path(r'^asset/ajax/alert_history_data', asset.ajax_alert_history_data, name='asset.ajax_alert_history_data'),
    re_path(r'^asset/ajax/status_history_data/(?P<asset_id>\d+)', asset.ajax_status_history_data, name='asset.ajax_status_history_data'),
    re_path(r'^asset/picker/(?P<asset_id>[^/.]+)/(?P<name>[^/.]+)/?', asset.picker, name='asset.picker'),
    re_path(r'^asset/status_grid/(?P<platform_id>\d+)', asset.status_grid, name='asset.status_grid'),
    re_path(r'^asset/gliders/(?P<group_id>\d+)', asset.glider_overview, name='asset.glider_overview'),
    re_path(r'^asset/clone/(?P<asset_id>[^/.]+)/?', asset.clone_asset, name='asset.clone_asset'),
    re_path(r'^asset/execute_clone_asset/?', asset.execute_clone_asset, name='asset.execute_clone_asset'),
    re_path(r'^asset/purge_asset/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.purge_asset, name='asset.purge_asset'),
    re_path(r'^asset/execute_purge_asset/?', asset.execute_purge_asset, name='asset.execute_purge_asset'),
    re_path(r'^asset/platforms/?', asset.manage_platforms, name='asset.manage_platforms'),
    re_path(r'^asset/classifications/?', asset.manage_classifications, name='asset.manage_classifications'),
    re_path(r'^asset/edit_platform/(?P<platform_id>\d+)', asset.edit_platform, name='asset.edit_platform'),
    re_path(r'^asset/edit_platform//?', asset.edit_platform, name='asset.edit_platform'),
    re_path(r'^asset/ajax/get_platform_details/(?P<platform_id>\d+)', asset.get_platform_details, name='asset.get_platform_details'),
    re_path(r'^asset/edit_classification/(?P<classification_id>\d+)', asset.edit_classification, name='asset.edit_classification'),
    re_path(r'^asset/edit_classification//?', asset.edit_classification, name='asset.edit_classification'),
    re_path(r'^asset/ajax/delete_classification/?', asset.delete_classification, name='asset.delete_classification'),

ui/webapp/urls.py
from django.urls import re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings

urlpatterns = [
    re_path(r'^$', lambda r: HttpResponseRedirect(settings.DASHBOARD_URL)),
    re_path(r'^admin/', admin.site.urls),
    # TODO: Re-implement
    # re_path(r'^settings/', include('livesettings.urls')),
    re_path(r'^', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ui/core/models/variable.py
from django.db import models
from ..models.asset import Asset, Deployment
from ..models.account import User
from ..db import exec_dict


class Variable(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    is_custom = models.BooleanField(default=False)
    asset = models.ForeignKey(Asset, related_name='variable', on_delete=models.CASCADE)
    deployment = models.ForeignKey(Deployment, null=True, blank=True, on_delete=models.CASCADE)
    erddap_id = models.CharField(max_length=100)
    units = models.CharField(max_length=50, null=True, blank=True)
    platform = models.ForeignKey(Asset, null=True, blank=True, related_name='+', on_delete=models.CASCADE)
    is_plottable = models.BooleanField(null=False, blank=False, default=True)
    interpolation_amount = models.DurationField(null=True, blank=True)
    change_interval = models.DurationField(null=True, blank=True)
    is_global = models.BooleanField(null=False, blank=False, default=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    expression = models.TextField(null=True, blank=True)

    class Meta:
        db_table = 'variable'

    def __str__(self):
        return self.name

    def get_asset_variables(self, asset_id, user_id):
        return exec_dict('get_asset_variables', (asset_id, user_id,))

    def get_usage(self):
        return [item["name"] for item in exec_dict("get_variable_usage", (self.id, ))]


class VariableComponent(models.Model):
    # TODO(mchagnon): The related_name fields may not be correct
    parent = models.ForeignKey(Variable, related_name='components', on_delete=models.CASCADE)
    child = models.ForeignKey(Variable, related_name='childVariable', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'variable_component'

ui/templates/variable/clone_l3_variable.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags %}

{% block topnav %}
    {% if variable.name %}
        <h1>Cloning Variable: <a id='linkEdit' href='/variable/edit_l3_variable/{{ variable.id }}'>{{ variable.name }}</a></h1>
    {% else %}
        <h1>Clone Variable</h1>
    {% endif %}
{% endblock %}

{% block content %}
<div id="clone-details" class="row">
    <div class="col-md-5 col-lg-4">
        <div class="x_panel">
            <div class="x_title">
                <h2>Clone {{ variable.name }} to:</h2>
                <div class="nav navbar-right panel_toolbox">
                    <a id="btn-clone" class="btn btn-sm btn-primary">Clone Variable</a>
                    <input type="hidden" id="variable_id" />
                    <input type="hidden" id="variable_asset_ids" />
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="row" id="dispositions">
                Disposition:
                {% for disposition in dispositions %}
                <label>
                    <input
                            type="checkbox"
                            data-value="{{ disposition.id }}"
                            {% if disposition.id in shown_dispositions %}checked="checked"{% endif %} >
                    {{ disposition.name }}
                </label>
                {% endfor %}
            </div>
            <div class="x_content">
                {% if not perms.core.clone_without_owning and variable.created_by != user %}
                <div class="alert alert-info">
                <strong>Note:</strong> All cloned variables will be owned by you, even if the original variables were shared, or owned by someone else
                </div>
                {% endif %}
                <div id="js-grid-target-assets"></div>
            </div>
            <div class="x_content" style="max-height:600px;overflow:auto;overflow-x:hidden">
                <table class="table table-striped table-bordered" id="target-assets-table">
                    <tbody>
                    {% if target_assets %}
                        {% for target_asset in target_assets %}
                            <tr class="{% if not target_asset.disposition_id in shown_dispositions %}hide{% endif %}"
                                data-disposition-id="{{ target_asset.disposition_id }}">
                                <td>
                                    <label>
                                    &nbsp;
                                    <input type="checkbox" name="target_asset" value="{{ target_asset.asset_id }}" />
                                        {% autoescape off %}{{ target_asset|asset_fullname }}{% endautoescape %}
                                    </label>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td>
                                There are no compatible assets to clone to.
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
        <a href="{% url 'variable.manage_l3_variables' %}" id="btnBack" class="btn btn-default">Back to Listing</a>
        <a id="btn-clone-bottom" class="btn btn-sm btn-primary">Clone Variable</a>
    </div>
    <div class="col-md-5 col-lg-4">
        <div class="x_panel">
            <div class="x_title">
                <h2>Variable Summary</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content alert-summary">
                <div id="variable-detail" class="dialog-box"></div>
                <form class="label-left">
                    <div class="form-group">
                        <label class="control-label">Variable: </label>
                        <span>{{ variable.name }}</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Created:</label>
                        <span>{{ variable.created|date:"n/j/y g:iA"|lower }} UTC</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Shared:</label>
                        <span>{{ variable.is_global }}</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Asset:</label>
                        <span>{{ variable.asset.code }}</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Platform:</label>
                        <span>{{ variable.asset.platform.code }}</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Expression:</label>
                        <br />
                        <span>{{ variable.expression }}</span>
                    </div>
                </form>
            </div>
        </div>
        <div class="x_panel">
            <div class="x_title">
                <h2>Variables</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="js-grid-variables"></div>
            </div>
            <div class="x_content">
                <table class="table table-striped table-bordered" id="variables-table">
                    <thead>
                        <tr>
                            <th>Variable Name</th>
                            <th>Linked Asset</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if variables %}
                        {% for variable in variables %}
                            <tr>
                                <td>{{ variable.name }}</td>
                                <td>{{ variable.asset.name }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="2">Variable has no variables.</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="loading-panel" class="row hidden">
    <div class="col-md-10 col-lg-8 text-center" style="padding-top:100px">
        <img src="/static//images/loading.gif" />
        <br /><br />
        <h2>Please wait while variable is being cloned.</h2>
    </div>
</div>
<div id="complete-details" class="row hidden">
    <div class="row">
        <div id="success-table" class="col-md-5 col-lg-4 hidden">
            <div class="x_panel">
                <div class="x_title">
                    <div class="text-success">The variable has been successfully cloned to the following assets. Refer to the list below for links to each of the cloned variables.</div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="js-success-assets"></div>
                </div>
                <div class="x_content" style="max-height:600px;overflow:auto;overflow-x:hidden">
                    <table class="table table-striped table-bordered" id="success-assets-table">
                        <tbody id="success-assets-table-body">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div id="failed-table" class="col-md-5 col-lg-4 hidden">
            <div class="x_panel">
                <div class="x_title">
                    <div class="text-danger">The cloning of the variable has failed for the following assets. Refer to the list below to verify that the monitored variables are compatible with the selected assets.</div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div id="js-failed-assets"></div>
                </div>
                <div class="x_content" style="max-height:600px;overflow:auto;overflow-x:hidden">
                    <table class="table table-striped table-bordered" id="failed-assets-table">
                        <tbody id="failed-assets-table-body">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5 col-lg-4">
            <a href="{% url 'variable.manage_l3_variables' %}" id="btnBack2" class="btn btn-default">Back to Listing</a>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">

</script>
<script type="text/javascript">
    $(function(){
        $("#dispositions input[type=checkbox]").click(function(){
            $("#dispositions input[type=checkbox]").each(function(){
                var id = $(this).attr('data-value');
                $("tr[data-disposition-id=" + id + "]").toggleClass('hide', !$(this).is(":checked"));

                if (!$(this).is(":checked")) {
                    $("tr[data-disposition-id=" + id + "] input[type=checkbox]").prop('checked', false);
                }
            });
        });

        $('#btn-clone, #btn-clone-bottom').click(function(e) {
            var target_asset_ids = '';
            $('input:checkbox[name=target_asset]:checked').each(function(index) {
                target_asset_ids += this.value + ',';
            });
            if (target_asset_ids.length > 0) {
                target_asset_ids = target_asset_ids.substring(0,target_asset_ids.length-1);
            }

            if (target_asset_ids.length > 0) {
                $('#loading-panel').toggleClass('hidden', false);
                $('#clone-details').toggleClass('hidden', true);

                $.ajax({
                    url: '{% url 'variable.execute_clone_variable' %}',
                    method:'POST',
                    data: {
                        'variable_id': {{ variable.id }},
                        'target_asset_ids': target_asset_ids
                    },
                    success: function(data) {
                        if (data) {
                            // console.log(data);

                            if (data.success && data.successful_assets.length > 0) {
                                Common.add_success_message('Variable has been successfully cloned to ' + data.successful_assets.length + ' asset(s).');
                            } else {
                                Common.add_failed_message('Variable was not successfully cloned. Please verify assets are compatible.');
                            }

                            $('#loading-panel').toggleClass('hidden', true);
                            $('#complete-details').toggleClass('hidden', false);

                            var successful_assets = data.successful_assets;
                            if (successful_assets.length > 0) {
                                var $success_table_body = $('#success-assets-table-body');
                                for (var i=0; i < successful_assets.length; i++) {
                                    $success_table_body.append("<tr><td><a href='/variable/edit_l3_variable/" + successful_assets[i].L3VarID + "'>" + successful_assets[i].AssetName + "</a></td></tr>");
                                }

                                $('#success-table').toggleClass('hidden', false);
                            }

                            var failed_assets = data.failed_assets;
                            if (failed_assets.length > 0) {
                                var $failed_table_body = $('#failed-assets-table-body');
                                for (var i=0; i < failed_assets.length; i++) {
                                    $failed_table_body.append("<tr><td>" + failed_assets[i].Message + "</td></tr>");
                                }

                                $('#failed-table').toggleClass('hidden', false);
                            }
                        }
                    }
                });
            } else {
                alert('Please select at least one asset to clone to.');
            }
        });
    });
    </script>
{% endblock %}

ui/templates/variable/confirm_import_l3_variables.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags %}

{% block topnav %}
        <h1>Confirm Import L3 Variables</h1>
{% endblock %}

{% block content %}

<div class="x_panel">
    <h4>Settings applied to ALL imported items:</h4>
    <form action="{% url 'variable.do_import_l3_variables' %}" method="POST">
        {% csrf_token %}
        <div class="x_panel">
            {% if perms.core.edit_shared_items %}
            <div>
                <input type="checkbox" name="override_global" id="id_override_global">
                <label class="control-label">Override 'Is Shared'</label>
            </div>
            <div class="x_panel">
                <div>
                    <label class="control-label">Is Shared</label>
                    {{ perms_form.is_global }}
                </div>
                <div class="form-group global">
                    <label class="control-label">{{ perms_form.owner.label_tag }}</label>
                    {{ perms_form.owner }}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="x_panel">
            <h5>These Variables are available for import:</h5>
            <table class="table table-striped table-bordered dataTable no-footer" id="name_table">
            </table>
        </div>
        <input type="hidden" name="filename" value="{{filename}}">  
        {% if matched_l3s %}
        <input type="submit" id="obj_import_id_submit" class="btn btn-primary" style="margin-top:5px" value="Import these Variables" >
        {% endif %}
    </form>
    {% if error_objs %}
        <h5>These Variables could not be matched to assets:</h5>
        {% for msg in error_objs %}
            <div style="display:inline-block">
            <div class="alert-error"> {{msg}}</div>
            </div>
        {% endfor %}
    {% endif %}

</div>


{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(function(){
        var l3_data = [
            {% for l3 in matched_l3s %}
            {
                "id": "{{l3.id}}", 
                "name": "{{l3.name}}",
            } ,
            {% endfor %}
        ]

        var tableId = '#name_table';
                
        let resultsTable = $(tableId).DataTable(
            {     
                dom: 'frtip',
                order: ([1,'asc']),
                data:l3_data,
                paging: false,
                select: true,
                searching: false,
                ordering: false,
                info: true,
                columns:[
                    {
                        title: "Select",
                        data:"id",
                        checkboxes: {
                            selectRow: true,
                        },
                        render: function(data, type, row) {
                            return '<input type="checkbox" name="obj_import_id" value="' + data + '" class="dt-checkboxes obj_import_id">';
                        }
                    },
                    {
                        title: "Name",
                        data:"name",
                        render: function(data, type, row) {
                            return '<input class="obj_import_name" type="text" style="min-width: 300px" name="obj_import_name_' + row.id + '" value="' + row.name + '" >';
                        }
                    }
                    
                ],
            }
        );
        $(tableId+' tbody').on( 'click', 'input[type="text"]', function (e) {
            e.stopPropagation();
        });

        var is_global_handler = function() {
            var is_global = $("#id_is_global").is(':checked');
            $(".form-group.global .owner").attr("disabled", is_global);
        };
        is_global_handler();
        $("#id_is_global").change(is_global_handler);


        var override_global_handler = function() {
            var override_global = $("#id_override_global").is(':checked');
            $("#id_is_global").attr("disabled", !override_global);
            is_global_handler();
        };

        override_global_handler();
        $("#id_override_global").change(override_global_handler);

        var obj_import_id_handler = function(){
            if($(".obj_import_id:checked").length>0){
                $("#obj_import_id_submit").removeAttr('disabled');
            }else{
                $("#obj_import_id_submit").prop("disabled", true);
            }
        };
        obj_import_id_handler();
        resultsTable.on("select", obj_import_id_handler);
        resultsTable.on("deselect", obj_import_id_handler);
    });
</script>

{% endblock %}

ui/templates/variable/do_import_l3_variables.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags %}

{% block topnav %}
        <h1>Import L3 Variables</h1>
{% endblock %}

{% block content %}

<div class="x_panel">
    
    <h5>Successfully imported these Variables:</h5>
    {% for l3 in l3s_imported %}
        <div><a href="{% url 'variable.edit_l3_variable' l3.id %}" > {{l3.name}}</a></div>
    {% endfor %}

    {% if error_objs %}
    <h5>These variables could not be matched to assets:</h5>
        {% for msg in error_objs %}
        <div style="display:block">
            <div style="display:inline-block">
                <div class="alert-error"> {{msg}}</div>
            </div>
        </div>
        {% endfor %}
    {% endif %}
</div>


{% endblock %}

{% block scripts %}

{% asset_picker_scripts 'assetpicker' %}

{% endblock %}

ui/templates/variable/import_l3_variables.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags %}

{% block topnav %}
        <h1>Import L3 Variables</h1>
{% endblock %}

{% block content %}

<div class="x_panel">
    <div class="x_content">
        <h2>Use the form below to upload plots exported from a backup or another OMS++ instance. The file being uploaded must end in .json.</h2>
        <div style="margin-bottom:10px;">
            {% if error_msg %}<div class="error-message">{{ error_msg }}</div>{% endif %}
        </div>
        <form method="POST" action="{% url 'variable.confirm_import_l3_variables' %}" enctype="multipart/form-data"  >
        {% csrf_token %}
        <div>
            {{form.file}}
            <div class="error-message">{% if form.file.errors %}{{ form.file.errors.as_text }}{% endif %}</div>
        </div>
        <input type="submit" class="btn btn-primary" style="margin-top:5px" value="Import JSON File"/>
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}

{% asset_picker_scripts 'assetpicker' %}

{% endblock %}