ui/core/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import reverse_lazy

from .forms.account import LoginForm
from .views import account, dashboard, alert, asset, plots, variable, plot

urlpatterns = [

    # /account
    re_path(r'^account/login/?$',
        auth_views.LoginView.as_view(
            template_name='account/login.html',
            authentication_form=LoginForm,
        ),
        name='account.login'),
    re_path(r'^account/logout/?$',
        auth_views.LogoutView.as_view(
            next_page=settings.LOGIN_URL
        ), name='account.logout'),

    re_path(r'^account/reset_password/',
        auth_views.PasswordResetView.as_view(success_url=reverse_lazy('password_reset_done'), template_name="registration/password_reset_form.html"),
        name="auth_password_reset"),

    re_path(r'^account/reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), 
        name="password_reset_done"),

    re_path(r'^account/reset/confirm/(?P<uidb64>[^/.]+)/(?P<token>[^/.]+)/',
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('password_reset_complete'), template_name="registration/password_reset_confirm.html"), 
        name="password_reset_confirm"),

    re_path(r'^account/reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), 
        name="password_reset_complete"),

    re_path(r'^account/myaccount/?$', account.my_account, name='account.my_account'),
    re_path(r'^account/preferences/?$', account.preferences, name='account.preferences'),
    re_path(r'^account/users/?$', account.users, name='account.users'),
    re_path(r'^account/default', account.default_page, name='account.default'),
    re_path(r'^account/edit_user/(?P<user_id>[^/.]*)/?', account.my_account, name='account.edit_user'),
    re_path(r'^account/add_user/?', account.my_account, name='account.add_user'),
    re_path(r'^account/delete_user', account.delete_user, name='account.delete_user'),
    re_path(r'^account/ajax/users', account.user_list, name='account.user_list'),

    # /dashboard
    re_path(r'^hotlist/?$', dashboard.overview, name='overview'),
    re_path(r'^dashboard/?$', dashboard.default_check, name='default_check'),
    re_path(r'^system/(?P<group_id>\d+)?$', dashboard.system_overview, name='dashboard.system_overview'),
    re_path(r'^system/ajax/system_overview_preference', dashboard.update_system_overview_preference, name='dashboard.update_system_overview_preference'),
    re_path(r'^system/power/(?P<platform_id>[^/.]+)/?', dashboard.power_details, name='dashboard.power_details'),
    re_path(r'^system/ajax/update_alert_disposition', dashboard.update_alert_by_disposition, name='dashboard.update_alert_by_disposition'),

    re_path(r'^system/backup_database', dashboard.backup_database, name='dashboard.backup_database'),
    re_path(r'^system/execute_backup_database', dashboard.execute_backup_database, name='dashboard.execute_backup_database'),

    # /alert
    re_path(r'^alert/resolve/(?P<alert_id>[^/.]+)/?', alert.resolve_alert_view, name='alert.resolve'),
    re_path(r'^alert/acknowledge/?', alert.acknowledge, name='alert.acknowledge'),
    re_path(r'^alert/update_status/?', alert.update_status, name='alert.update_status'),
    re_path(r'^alert/(?P<alert_id>\d+)/$', alert.detail, name='alert.detail'),
    re_path(r'^alert/(?P<alert_id>\d+)/(?P<is_resolve>[^/.]+)/?', alert.detail, name='alert.detail'),
    re_path(r'^alert/save_note/(?P<alert_id>\d+)/?', alert.save_note, name='alert.save_note'),
    re_path(r'^alert/ajax/get_notes/(?P<alert_id>\d+)/?', alert.get_notes, name='alert.get_notes'),
    re_path(r'^alert/ajax/get_occurrences/(?P<alert_id>\d+)/?', alert.get_occurrences, name='alert.get_occurrences'),
    re_path(r'^alert/ajax/view_trigger/(?P<trigger_id>[^/.]+)/?', alert.view_trigger, name='alert.view_trigger'),
    re_path(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    re_path(r'^alert/create_manual/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', alert.create_manual, name='alert.create_manual'),
    re_path(r'^alert/manage_subscriptions/(?P<asset_id>\d+)/?', alert.manage_subscriptions, name='alert.manage_subscriptions'),
    re_path(r'^alert/edit_trigger/(?P<trigger_id>\w+)/(?P<asset_id>\w+)/$', alert.edit_trigger, name='alert.edit_trigger'),
    re_path(r'^alert/edit_trigger/(?P<trigger_id>[^/.]+)/?', alert.edit_trigger, name='alert.edit_trigger'),
    re_path(r'^alert/edit_trigger/?$', alert.edit_trigger, name='alert.edit_trigger'),
    re_path(r'^alert/clone_trigger/(?P<trigger_id>[^/.]+)/?', alert.clone_trigger_page, name='alert.clone_trigger_page'),
    re_path(r'^alert/execute_clone_trigger/?', alert.execute_clone_trigger, name='alert.execute_clone_trigger'),
    re_path(r'^alert/manage_triggers/?$', alert.manage_triggers, name='alert.manage_triggers'),
    re_path(r'^alert/ajax/trigger_list/?$', alert.trigger_list, name='alert.trigger_list'),
    re_path(r'^alert/ajax/delete_trigger/?$', alert.delete_trigger, name='alert.delete_trigger'),
    re_path(r'^alert/ajax/purge_trigger/?$', alert.purge_trigger, name='alert.purge_trigger'),
    re_path(r'^alert/export_triggers/?$', alert.export_triggers, name='alert.export_triggers'),
    re_path(r'^alert/import_triggers/?$', alert.import_triggers, name='alert.import_triggers'),
    re_path(r'^alert/confirm_import_triggers/?$', alert.confirm_import_triggers, name='alert.confirm_import_triggers'),
    re_path(r'^alert/do_import_triggers/?$', alert.do_import_triggers, name='alert.do_import_triggers'),
    re_path(r'^alert/ajax/trigger_variable_list/(?P<trigger_id>[^/.]+)/?', alert.trigger_variable_list, name='alert.trigger_variable_list'),
    re_path(r'^alert/ajax/saved_variable_list/?', alert.saved_variables_list, name='alert.saved_variables_list'),
    re_path(r'^alert/ajax/alert_notification_list/(?P<alert_id>[^/.]+)/?', alert.alert_notification_list, name='alert.alert_notification_list'),
    re_path(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    re_path(r'^alert/ajax/get_trigger_by_id/(?P<trigger_id>[^/.]+)/?', alert.get_trigger_by_id, name='alert.get_trigger_by_id'),
    re_path(r'^alert/create_redmine_issue/(?P<alert_id>\d+)/?$', alert.create_redmine_issue, name='alert.create_redmine_issue'),
    re_path(r'^alert/confirm_redmine_issue/(?P<alert_id>\d+)/?$', alert.confirm_redmine_issue, name='alert.confirm_redmine_issue'),
    re_path(r'^alert/ajax/redmine_trackers/(?P<project_id>\d+)/?$', alert.redmine_trackers, name='alert.redmine_trackers'),
    re_path(r'^alert/ajax/redmine_tracker_details/(?P<tracker_id>\d+)/?$', alert.redmine_tracker_details, name='alert.redmine_tracker_details'),
    re_path(r'^alert/ajax/refresh_notifications/?', alert.refresh_notifications, name='alert.refresh_notifications'),
    re_path(r'^redmine/confirm_redmine_issue/(?P<issue_id>\d+)/?$', alert.confirm_redmine, name='redmine.confirm_redmine'),

    # /asset
    re_path(r'^asset/overview/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.overview, name='asset.overview'),
    re_path(r'^asset/parsed_data/(?P<asset_id>[^/.]+)/?', asset.parsed_data, name='asset.parsed_data'),
    re_path(r'^asset/parsed_data_for_file/(?P<asset_id>[^/.]+)/?', asset.parsed_data_for_file, name='asset.parsed_data_for_file'),
    re_path(r'^asset/parsed_data_for_plot/(?P<asset_id>[^/.]+)/?', asset.parsed_data_for_plot, name='asset.parsed_data_for_plot'),
    re_path(r'^asset/group/(?P<group_id>[^/.]+)/?', asset.group_overview, name='asset.group_overview'),
    re_path(r'^asset/map/(?P<group_id>[^/.]+)/?', asset.group_mooring_locations, name='asset.group_mooring_locations'),
    re_path(r'^asset/plot-data/?', asset.plot_data, name='asset.plot_data'),
    re_path(r'^asset/ajax/alert_history_data', asset.ajax_alert_history_data, name='asset.ajax_alert_history_data'),
    re_path(r'^asset/ajax/status_history_data/(?P<asset_id>\d+)', asset.ajax_status_history_data, name='asset.ajax_status_history_data'),
    re_path(r'^asset/picker/(?P<asset_id>[^/.]+)/(?P<name>[^/.]+)/?', asset.picker, name='asset.picker'),
    re_path(r'^asset/status_grid/(?P<platform_id>\d+)', asset.status_grid, name='asset.status_grid'),
    re_path(r'^asset/gliders/(?P<group_id>\d+)', asset.glider_overview, name='asset.glider_overview'),
    re_path(r'^asset/clone/(?P<asset_id>[^/.]+)/?', asset.clone_asset, name='asset.clone_asset'),
    re_path(r'^asset/execute_clone_asset/?', asset.execute_clone_asset, name='asset.execute_clone_asset'),
    re_path(r'^asset/purge_asset/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.purge_asset, name='asset.purge_asset'),
    re_path(r'^asset/execute_purge_asset/?', asset.execute_purge_asset, name='asset.execute_purge_asset'),
    re_path(r'^asset/platforms/?', asset.manage_platforms, name='asset.manage_platforms'),
    re_path(r'^asset/classifications/?', asset.manage_classifications, name='asset.manage_classifications'),
    re_path(r'^asset/edit_platform/(?P<platform_id>\d+)', asset.edit_platform, name='asset.edit_platform'),
    re_path(r'^asset/edit_platform//?', asset.edit_platform, name='asset.edit_platform'),
    re_path(r'^asset/ajax/get_platform_details/(?P<platform_id>\d+)', asset.get_platform_details, name='asset.get_platform_details'),
    re_path(r'^asset/edit_classification/(?P<classification_id>\d+)', asset.edit_classification, name='asset.edit_classification'),
    re_path(r'^asset/edit_classification//?', asset.edit_classification, name='asset.edit_classification'),
    re_path(r'^asset/ajax/delete_classification/?', asset.delete_classification, name='asset.delete_classification'),

ui/webapp/urls.py
from django.urls import re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings

urlpatterns = [
    re_path(r'^$', lambda r: HttpResponseRedirect(settings.DASHBOARD_URL)),
    re_path(r'^admin/', admin.site.urls),
    # TODO: Re-implement
    # re_path(r'^settings/', include('livesettings.urls')),
    re_path(r'^', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ui/core/forms/asset.py
import re
from django import forms

from ..models import Asset
from ..models.asset import AssetDisposition, AssetDispositions, AssetCategory, AssetSubcategory, AssetClassification
from ..models.asset import Group


class PlatformForm(forms.Form):
    disposition = forms.ChoiceField()
    category = forms.ChoiceField()
    subcategory = forms.ChoiceField(required=False)

    deployment_date = forms.CharField(required=False, label='Deployment Date', widget=forms.DateTimeInput(attrs={'class': 'datetimepicker deployment_date'}, format="%m/%d/%y %I:%M%p"))
    deployment_cruise = forms.CharField(required=False, label='Deployment Cruise', max_length=100)
    recovery_date = forms.CharField(required=False, label='Recovery Date', widget=forms.DateTimeInput(attrs={'class': 'datetimepicker recovery_date'}, format="%m/%d/%y %I:%M%p"))
    recovery_cruise = forms.CharField(required=False, label='Recovery Cruise', max_length=100)

    lat = forms.FloatField(required=False, widget=forms.TextInput())
    lon = forms.FloatField(required=False, widget=forms.TextInput())
    depth = forms.FloatField(required=False, widget=forms.TextInput())
    watch_circle_radius = forms.FloatField(required=False, widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(PlatformForm, self).__init__(*args, **kwargs)

        self.fields['disposition'] = forms.ChoiceField(
            choices=tuple(AssetDisposition.objects.all().values_list('id', 'name')),
            widget=forms.Select(attrs={'class': 'form-control'})
        )

        categories = AssetCategory.objects.all().values_list("id", "name")
        categories = [(0, "Select a Category")] + list(categories)

        self.fields['category'] = forms.ChoiceField(
            choices=categories,
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )

        subcategories = AssetSubcategory.objects.all().values_list("id", "name")
        subcategories = [(0, "Select a Subcategory")] + list(subcategories)

        self.fields['subcategory'] = forms.ChoiceField(
            choices=subcategories,
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )
    
    def clean(self):
        self.cleaned_data = super(PlatformForm, self).clean()

        if (self.cleaned_data.get('lat') and not self.cleaned_data.get('lon') or
            self.cleaned_data.get('lon') and not self.cleaned_data.get('lat')):
            raise forms.ValidationError("Please enter both Latitude and Longitude")

        return self.cleaned_data


class EditAssetForm(forms.ModelForm):
    GLOB_REGEX = r'^[a-zA-Z0-9\_\-\/\*\.]{5,}$'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_raw_data_glob(self):
        data = self.cleaned_data.get('raw_data_glob')

        if data and not re.match(self.GLOB_REGEX, data):
            raise forms.ValidationError("Please enter a valid path")

        return data

    def clean_parsed_data_glob(self):
        data = self.cleaned_data.get('parsed_data_glob')

        if data and not re.match(self.GLOB_REGEX, data):
            raise forms.ValidationError("Please enter a valid path")

        return data

    def clean_reference_designator(self):
        data = self.cleaned_data.get('reference_designator')

        if data and not re.match(r'^[a-zA-Z0-9-]+$', data):
            raise forms.ValidationError("Only letters, numbers and dashes are allowed")

        return data

    def clean_serial_number(self):
        data = self.cleaned_data.get('serial_number')

        if data and not re.match(r'^[a-zA-Z0-9-]+$', data):
            raise forms.ValidationError("Only letters, numbers and dashes are allowed")

        return data

    class Meta:
        model = Asset
        fields = ('parsed_data_glob', 'raw_data_glob', 'reference_designator', 'serial_number', )
        widgets = {
            'parsed_data_glob': forms.TextInput(attrs={'class': 'form-control'}),
            'raw_data_glob': forms.TextInput(attrs={'class': 'form-control'}),
            'reference_designator': forms.TextInput(attrs={'class': 'form-control'}),
            'serial_number': forms.TextInput(attrs={'class': 'form-control'}),
        }


class ClassificationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ClassificationForm, self).__init__(*args, **kwargs)

        self.fields['description'].required = False
        self.fields['pattern'].required = False

    def clean(self):
        data = self.cleaned_data

        return data

    class Meta:
        model = AssetClassification
        fields = ('name', 'abbreviation', 'description', 'is_virtual', 'pattern')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 10, 'style': 'width:100%;height:150px'})
        }


class ImportPlatformForm(forms.Form):
    platform_code = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    deployment_code = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    disposition = forms.ModelChoiceField(
        queryset=AssetDisposition.objects.all(),
        required=False,
        empty_label=None,
        widget=forms.Select(attrs={'class': 'form-control'}))
    category = forms.ChoiceField(required=False)
    subcategory = forms.ChoiceField(required=False)
    group = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(ImportPlatformForm, self).__init__(*args, **kwargs)

        cats = AssetCategory.objects.all()
        cat = []
        cat.append([0, 'Select a Category'])
        for c in cats:
            cat.append([c.id, c.name])

        self.fields['category'] = forms.ChoiceField(
            choices=tuple(cat),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )
        subcat = []
        subcat.append([0, 'Select a Subcategory'])
        subcats = AssetSubcategory.objects.all()
        for sub in subcats:
            subcat.append([sub.id, sub.name])
        self.fields['subcategory'] = forms.ChoiceField(
            choices=tuple(subcat),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )

        groups = [
            (g['id'], g['name'])
            for g in Group.objects.order_by('name').values('id', 'name')
        ]

        self.fields['group'] = forms.ChoiceField(
            choices=[('', 'Auto-Detect'), *groups],
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )

ui/templates/asset/glider_overview.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags status_tags %}

{% block topnav %}
<h1>{{ group.display_name }}</h1>
{% endblock %}

{% block content %}
<div class="clearfix"></div>
{% for num, group in plat_dict.items %}
<div class="row row-eq-height">
    {% for glider in group %}
    {% for glider_name, all_glider_data in glider.items %}
    <div class="col-lg-4">
        <div class="x_panel glider">
            <div class="x_title">
                <h2>{{ glider_name }} {% if all_glider_data.latest_time %}({{ all_glider_data.latest_time|date:"n/j/y"|lower }}){% endif %}</h2>
                <div class="clearfix"></div>
            </div>
            {% for asset in all_glider_data.glider_deployments %}
            <div class="x_content">
                <div class="row">
                    <div class="col-lg-3">
                        <div>
                            {# last_update could be None or some date #}
                            {% if asset.last_update and asset.is_data_recent %}
                                <i class="fa fa-circle circle-glider-status-ok glider-status-circle"
                                    title="Updated: {% if asset.last_update %}{{asset.last_update|date:'n/j/y'|lower}}{% endif %}">
                                </i>
                            {% else %}
                                <i class="fa fa-circle circle-status-error glider-status-circle"
                                   title="Updated: {% if asset.last_update %}{{asset.last_update|date:'n/j/y'|lower}}{% else %}data not available{% endif %}">
                                </i>
                            {% endif %}
                            {{asset.deployment.name}}
                        </div>
                    </div>
                    <div class="col-lg-9 text-right glider-links">
                        <a href="{{ asset.erddap_data_url }}" target="_blank">ERDDAP Data</a> |
                        <a href="{{ asset.erddap_graph_url }}" target="_blank">ERDDAP Graphs</a>
                        {% if asset.raw_data_dir %}
                        | <a href="{{ asset.raw_data_dir }}" target="_blank">Raw Data</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    {% endfor %}
</div>
{% endfor %}


{% endblock %}

ui/templates/asset/group_mooring_locations.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags status_tags %}

{% block topnav %}
    <h1>{{ group.display_name }} -- Mooring Map {% if specific_platform_code %} ({{specific_platform_code}}) {% endif %}</h1>
{% endblock %}

{% block content %}
<div id="map">
    <div id="no-data-tag"><h1>No Data Available</h1></div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        let groupDataId = 'group-{{ group.id }}';
        SetupCurrentSideNavMenu(groupDataId, null);
    });

    // https://github.com/pointhi/leaflet-color-markers

    document.addEventListener('DOMContentLoaded', function() {
        let allMooringsGroup = L.featureGroup([]);
        let activeMooringGroup = L.featureGroup([]);
        let time_position_array;
        let watch_circle;
        let headMarker;

        let config = {};

        let moorings = [];
        let mrg;

        config.fallback_position = {{fallback_position}};
        {% for mooring in output_mooring_data %}

            mrg = {}
            // time_position_array is in this format: [time, lat, lon]
            time_position_array = {{ mooring.time_position_array }};
            if (time_position_array[0]>time_position_array.slice(-1)[0]) {
                time_position_array.reverse();
            }

            // add the watch circle to the plot first so the other markers are drawn on top
            // watch_circle = {{ mooring.watch_circle_data }}
            mrg.watch_circle = {{ mooring.watch_circle_data }};
            mrg.platform_code = '{{ mooring.platform_code }}';
            mrg.platform_id = '{{ mooring.platform_id }}';
            mrg.deployment_code = '{{ mooring.deployment_code }}';
            mrg.alerts = '{{ mooring.alerts }}';
            mrg.time_position_array = time_position_array;

            moorings.push(mrg);

        {% endfor %}

        config.moorings = moorings;

        Pages.MooringLocations.init(config);

    });
</script>
{% endblock %}

ui/templates/asset/import_platform.html
{% extends 'base.html' %}
{% load static %}

{% block topnav %}
    <h1>Import Platform</h1>
{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <form method="post" class="form-horizontal form-label-left" id="import-form">
            <input type="hidden" name="confirmed" id="confirmed" />
            {% csrf_token %}

        <div class="row">
            <div class="col-md-5">
                <div class="x_panel">
                    <div class="x_title">Platform Details</div>
                    <div class="x_content">
                        <div class="form-group">
                            <label class="control-label col-md-4">Platform Code</label>
                            <div class="col-md-8">
                                {% if ready_for_import %}
                                    <div class="form-control-static">{{ form.platform_code.value|default_if_none:"" }}</div>
                                    <input type="hidden" name="platform_code" value='{{ form.platform_code.value|default_if_none:"" }}' />
                                {% else %}
                                    <span class="form-control-static">{{ form.platform_code }}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Deployment Code</label>
                            <div class="col-md-8">
                                {% if ready_for_import %}
                                    <div class="form-control-static">{{ form.deployment_code.value|default_if_none:"" }}</div>
                                    <input type="hidden" name="deployment_code" value='{{ form.deployment_code.value|default_if_none:"" }}' />
                                {% else %}
                                    <span class="form-control-static">{{ form.deployment_code }}</span>
                                {% endif %}
                            </div>
                        </div>
                        {% if ready_for_import %}
                        <div class="form-group">
                            <label class="control-label col-md-4">Group</label>
                            <div class="col-md-8">
                                {{ form.group }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Category</label>
                            <div class="col-md-8">
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Subcategory</label>
                            <div class="col-md-8">
                                {{ form.subcategory }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Disposition</label>
                            <div class="col-md-8">
                                {{ form.disposition }}
                                <p class='invalid-input'>{% if form.disposition.errors %}{{ form.disposition.errors.as_text }}{% endif %}</p>
                            </div>
                        </div>
                        {% endif %}
                        {% if not ready_for_import %}
                        <div class="form-group">
                            <label class="control-label col-md-4"></label>
                            <div class="col-md-8">
                                <button type="submit" class="btn btn-primary btn-sm">Verify Information</button>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if verified %}
            <div class="col-md-6">
                {% csrf_token %}
                {% if existing_asset and not import_succeeded %}
                <div class="alert alert-info text-center">
                    The selected platform/deployment has already been imported. <br />You can view the platform below, or proceed with importing the new platform config and overwrite the existing platform.
                </div>
                <div class="text-center">
                    <a href="{% url 'asset.overview' existing_asset.id existing_asset.deployment.code %}" class="btn btn-primary btn-sm">View Platform</a>
                    <button type="submit" class="btn btn-danger btn-sm" id="confirm-import">Import Platform/Mooring</button>
                </div>
                {% endif %}

                {% if missing_config %}
                <div class="alert alert-danger text-center">
                    A platform configuration file for the platform/deployment could not be located
                </div>
                {% endif %}

                {% if ready_for_import %}
                <div class="alert well">
                    <p>A platform configuration file was found for this platform/deployment, and it has not already been imported. Please review the configuration file and data before completing the import process</p>
                    <br />
                    <div class="text-center">
                        <a href="{{ data_url }}" target="_blank" class="btn btn-default btn-sm">View Data Directory</a>
                        <a href="{{ config_url }}" target="_blank" class="btn btn-default btn-sm">View Platform Config</a>
                        <button type="submit" class="btn btn-primary btn-sm" id="confirm-import">Import Platform/Mooring</button>
                    </div>

                    <div id="import-platform-loading">
                        <p>Importing platform from the platform configuration file. Please wait...</p>
                        <img src="{% static 'images/loading.gif' %}" />
                    </div>
                </div>
                {% endif %}

                {% if import_failed %}
                <div class="alert alert-danger text-center">
                    <p>The platform/deployment failed to import: {{ import_message }}</p>
                </div>
                {% endif %}

                {% if import_succeeded %}
                <div class="alert alert-success text-center">
                    <p>The platform/deployment has been successfully imported</p>
                </div>
                <p class="text-center">
                    <a href="{% url 'asset.overview' new_asset.id new_asset.deployment.code %}" class="btn btn-primary btn-sm">View Platform</a>
                </p>
                {% endif %}
            </div>
            {% endif %}
        </div>

        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $("#id_category").on('change', function() {
        var id = $("#id_category option:selected").val();
        getSubcategories(id, 0);
    });

    $(function() {
        $("#confirm-import").click(function(){
            $("#import-platform-loading").show();
            $("#confirmed").val(true);

            return true;
        });

        $("#import-form").submit(function(){
            if ($("#confirmed").val() == "true") {
                $(this).attr('disabled','disabled');
            }
        });

        var flag = '{{ update_successful }}';
        if($("#id_category option:selected").val() != '0') {
            var id = $("#id_category option:selected").val();
            var sub_id = $("#id_subcategory option:selected").val();
            getSubcategories(id, sub_id);
        }
        else if(flag != 'True' && $("#id_category option:selected").val() == '0') {
            $("#id_subcategory").find('option').remove();
            $("#id_subcategory").append($('<option value="0">Select a Subcategory</option>'));
        }


        {% if ready_for_import %}
            $("#id_disposition").val({{ default_disposition }});
        {% endif %}
    });

    function getSubcategories(id, selected) {
        if (id === "")
            return;

        $.ajax({
            url: "{% url 'asset.subcategories' %}",
            method: 'POST',
            data: { 'id': id },
            success: function(response) {
                $("#id_subcategory").find('option').remove();

                if (response.data && response.data.length > 0)
                {
                    for (var i = 0; i < response.data.length; i++) {
                        var subcategory = response.data[i];
                        var selectedAttr =  subcategory.id == selected ? " selected" : "";

                        $("#id_subcategory").append(
                            $("<option value='" + subcategory.id + "'" + selectedAttr + ">" + subcategory.name + "</option>")
                        );
                    }
                }
            }
        });
    };


</script>
{% endblock %}

ui/templates/asset/status_grid.html
{% load status_tags %}
{% status_grid platform.id platform.id platform.deployment.code callback=callback show_platform=True %}